### ISSUE TITLE
Upload shortcut does not work

### ISSUE THREAD

**Issue by kovmir** [pldubouilh/gossa#109]
I use gossa tag `v1.0.0`. My setup is `dwm` and `librewolf`. Nothing happens if I hit `Ctrl + U`, file picker does not appear. However, file picker works if I click the upload icon.

Also, do not hide the upload icon on desktop, please!

**Comment by kovmir** [comment]
`<input> picker was blocked due to lack of user activation.` is what I get in console each time I hit `ctrl+u`.

**Comment by pldubouilh** [comment]
Ah right, that's an issue I saw in the past indeed, it's a limitation from the browser, where a user interaction is required in order to be able to catch keyboard actions. The fix mentioned feels like a bug in Firefox though 🫠  
I'll close this up for the time being :+1:

**Comment by pldubouilh** [comment]
> Also, do not hide the upload icon on desktop, please!

@kovmir regarding this, I think I'll allow custom JS to be injected from the CLI in a future release. Also it'll help with #110, etc...

**Comment by kovmir** [comment]
Why do you not want to include this natively? Unlike the keyboard shortcut, it works every time.
