### ISSUE TITLE
can't press Ctrl/Cmd + h to see all the UI/keyboard shortcuts.

### ISSUE THREAD

**Issue by ludetie** [pldubouilh/gossa#111]
Hello,

I can't press Ctrl/Cmd + h to see all the UI/keyboard shortcuts.
I don't have CMD key and Ctrl +h Keyboard shortcut is already configured in my browser.
What are these shortcuts ?

Thank you.

**Comment by kovmir** [comment]
* `Arrows/Enter`	browse files/folders and pictures
* `Ctrl/Meta + Enter`	download selected item as archive
* `Ctrl/Meta + C`	copy URL to clipboard
* `Ctrl/Meta + E`	rename item
* `Ctrl/Meta + Backspace`	delete item
* `Ctrl/Meta + U`	upload new file/folder
* `Ctrl/Meta + M`	create a new directory
* `Ctrl/Meta + X`	cut selected path
* `Ctrl/Meta + V`	paste previously selected paths to directory
* `Ctrl + click`	download selected item as archive
* `click file icon` 	rename item
* `double click file icon`	delete item
* `drag-and-drop item on UI`	move item
* `drag-and-drop external item`	upload file/folders
* `any other letter`	fuzzy search

**Comment by pldubouilh** [comment]
Hi @ludetie, what's your OS and Browser ? The shortcuts mentioned above by @kovmir work fine on chrome/firefox on linux and mac, but it may not work on other platforms !

**Comment by kovmir** [comment]
> Hi @ludetie, what's your OS and Browser ? The shortcuts mentioned above by @kovmir work fine on chrome/firefox on linux and mac, but it may not work on other platforms !

He said `Ctrl+h Keyboard shortcut is already configured in my browser` which is ambiguous, I know, but that being said means there is no issue/bug with `gossa`.

**Comment by pldubouilh** [comment]
Indeed, I think it might be related to #109, where shortcuts are not caught if there's no user-interaction on the page.
I'll close this one for now :+1:
