### ISSUE TITLE
Symlinks Don't Work

### ISSUE THREAD

**Issue by jtitley** [pldubouilh/gossa#121]
I'm trying to get directory symlinks set up so I can host multiple directories. But it doesn't seem to work.  I'm assuming the links need to be from the context of the container, but no matter what i do, the symlink directories just don't show up.

Snippet from Docker Compose:
    volumes:
      - /home/josh/gossa:/shared:ro  # Video directory mounted as read-only
      - /mnt/video:/video:ro
      - /mnt/Drive:/drive:ro
    entrypoint: ["/gossa", "-symlinks", "-verb", "-ro", -h, "0.0.0.0", "-p", "8001", "/shared"] 

My directory:

ln -s /video /home/josh/gossa/video
ln -s /drive /home/josh/gossa/drive

**Comment by pldubouilh** [comment]
Odd - I just re-tested it manually and it works fine. Are you sure your symlinks are valid ? I tested both valid and invalid symlinks, gossa filters out the invalid one (complains in the logs `error - cant stat a file stat /home/joe/test/bbb: no such file or directory`) but the valid one shows up.

It may also be a limitation with how it's mounted by docker-compose.

**Comment by jtitley** [comment]
What a great tip. I didn't even think of mounting volumes in the share directory. Thanks for the quick reply, it works great!
