### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by hpka** [pldubouilh/gossa#16]
Great project. I was thinking it might be a good idea to put one of the dockerfiles, perhaps the caddy one, up on Docker Hub?

Truth is I was looking for an easy way to add it to UnRAID and thought this might be best.

**Comment by pldubouilh** [comment]
thanks @hpka ! I was thinking of updating the dockerfile and pushing it to docker up as well, I'll do that soon :+1:

**Comment by pldubouilh** [comment]
that should be it : https://hub.docker.com/r/pldubouilh/gossa/tags
I pushed the "download" dockerfile, as the caddy one embeds the config (and has test/hardcoded credentials) 
keep me posted if it doesn't work for you
