### ISSUE TITLE
Upload via click

### ISSUE THREAD

**Issue by eikek** [pldubouilh/gossa#18]
Thanks for this nice tool!

I saw the issue #8, but unfortunately I'm not able to find the control on the ui to click for uploading files. What am I missing?

**Comment by pldubouilh** [comment]
thanks @eikek! The icon pops up (cf first icon on image below) when the width is below a certain threshold (800px iirc). It works fine on my phone - is it not working on your device ? 

![Screenshot from 2019-03-13 22-55-40](https://user-images.githubusercontent.com/760637/54328141-2e687080-45e3-11e9-9301-2759a918ce35.png)

**Comment by eikek** [comment]
Ah, I see! I'm not on a phone or small device. I use a tiling (and
keyboard driven) window manager. So I don't use drag&drop, because I
don't have tools to drag from. Would it maybe be possible to always
show this icon using a config value (maybe `max-width` or `min-width`
or so)?

**Comment by pldubouilh** [comment]
Maybe a keyboard shortcut like `ctrl+u` could do the trick ?
I'll see if I can fit the icon as well.

**Comment by eikek** [comment]
Ah sure, a keyboard shortcut would be fine, too. Even better :)

**Comment by pldubouilh** [comment]
done #19 :+1:

**Comment by eikek** [comment]
:+1:  Great, thank you!!!

**Comment by kovmir** [comment]
@pldubouilh I use a tiling window manager as well, drag & drop is not an option for me. Could you please not hide it on desktop?
