### ISSUE TITLE
Run behind reverse path based

### ISSUE THREAD

**Issue by r3r57** [pldubouilh/gossa#25]
Currently, this can't be run behind a path based reverse proxy.
Are there any plans to implement this feature?

Otherwise I'll implement it by myself if it does not require too many modifications and do a PR.

**Comment by pldubouilh** [comment]
good catch, never bumped on it so far, so it wasn't planned. 
I had a look - it looks trivial server side, but it seems a few changes would be needed ui side. I'll take a look :+1:

**Comment by r3r57** [comment]
Yes, server side seems easy,  but gossa-ui requires lot more changes.

**Comment by pldubouilh** [comment]
@r3r57 right - I implemented this in #26 - feel free to have a look and play with it :+1:
