### ISSUE TITLE
investigate a go fuse client

### ISSUE THREAD

**Issue by pldubouilh** [pldubouilh/gossa#27]
https://github.com/bazil/fuse

**Comment by vaidd4** [comment]
After learning a bit about FUSE I don't really see the usage here. Gossa is used to read the actual filesystem.
What would be the use of fuse ? (really interrested to hear about)

**Comment by pldubouilh** [comment]
yep - I'm not sure either.

my idea was to be able to spin a simple gossa+authenticated proxy on a server, and have a fuse implementation to access it remotely from a client's filesystem. A bit like ssh/sshfs ; gossa+proxy would act in the same fashion as a ssh server, and a go client would act as sshfs.

but then I recalled I wrote gossa to avoid dealing with fuse/samba :smile: also ssh and sshfs work abolutely fine
