### ISSUE TITLE
File sorting is case-sensitive

### ISSUE THREAD

**Issue by sbrl** [pldubouilh/gossa#29]
Consider the following filenames:

```
cover.png
Some Track.mp3
```

The order shown above is what you'd expect, but this is how gossa would order it:

```
Some Track.mp3
cover.png
```

Looks to me like it's not being case-sensitive when sorting.

Just to be awkward, these are also valid filenames:

```
Í'm being awkward.txt
ỳay.c
€5.md
©®eam on the cake.js
```

I'm also writing a review / tutorial blog post about Gossa, as I'm really impressed with it's ease of use - thanks for awesome software!

**Comment by pldubouilh** [comment]
thanks :) 

yep, it's because of the sorting on `ReadDir`'s side : [it's line 106](https://golang.org/src/io/ioutil/ioutil.go?s=2978:3029#L76) - ll have a look!

**Comment by sbrl** [comment]
Awesome, thanks :D

I've also [packaged it into my apt repository](https://apt.starbearainbowlabs.com/) (as `gossa`), if you're interested. The packaging process is automatic, but currently I'm manually triggering it whenever there's a new release - though I'm hoping to change this.

**Comment by CrashLaker** [comment]
Hi. Is it possible to add sort by other options like modified date?

thanks!

**Comment by sbrl** [comment]
@CrashLaker: That sounds like a separate issue.

**Comment by pldubouilh** [comment]
@sbrl coming in #37 - cheers for the deb btw :) I'll probably make a ppa when time allows

@CrashLaker will think about it - I'll open a separate issue

**Comment by sbrl** [comment]
No problem, @pldubouilh :smiley_cat:

If I haven't triggered the update to my repo in 24 hours (it goes through at 2am GMT every night), email me and I'll get it sorted.
