### ISSUE TITLE
Docker image runs gossa as root by default

### ISSUE THREAD

**Issue by jeslinmx** [pldubouilh/gossa#31]
Running by root works out fine if the files being shared by gossa are exclusively being used by gossa. However, for example, I am using syncthing to sync my files between my vps, my desktop and my phone, but also want to make my files available through a web ui, and so am using gossa for this purpose. It is not ideal to have gossa running as root in this case, as new files and folders will be owned by root:root.

The ability to set the uid and gid of the processes within the container through an environment variable is common in several widely used images of popular server apps (e.g. [wonderfall/nextcloud](https://hub.docker.com/r/wonderfall/nextcloud), [linuxserver/syncthing](https://hub.docker.com/r/linuxserver/syncthing)). I could make a PR for this if this is of interest to anyone?

**Comment by pldubouilh** [comment]
thanks for the PR :+1:
