### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by sunlewuyou** [pldubouilh/gossa#39]
First of all this tool is really good! One requirement: It is recommended to add user authentication function, thank you! stay tuned!

**Comment by pldubouilh** [comment]
thanks, happy it's useful :) 
I left authentication out of the scope of this project on purpose. Middlewares/proxies are better fit for handling tls and authentication, and it also keeps the gossa codebase smaller and easier to read.

For instance you can use [Caddy](https://caddyserver.com/) for this. I included a [sample caddy config](https://github.com/pldubouilh/gossa/blob/master/support/Caddyfile), which sets up valid https + authentication in a 4 lines config :+1: 
you can either use it with docker (there's a caddy/gossa docker file in the same folder), or just starting both gossa and caddy manually.

**Comment by pldubouilh** [comment]
btw, you can also route different users to different backends (pointing to different folders, or readonly for instance) using caddy. It's pretty straightforward, but maybe I'll add a sample config to the example folder as well :+1:

**Comment by sunlewuyou** [comment]
Thank you for your suggestions and examples! wish you a happy life!

**Comment by sunlewuyou** [comment]
It is still recommended that you add user authentication. Validation using third-party tools is not always lightweight enough.
