### ISSUE TITLE
the file name cannot be automatically refreshed

### ISSUE THREAD

**Issue by sunlewuyou** [pldubouilh/gossa#41]
After uploading the file, the file name cannot be automatically refreshed. I need to refresh it manually. I don't know what caused it. And this does not happen every time.

**Comment by sunlewuyou** [comment]
For newly uploaded files, the file name cannot be refreshed automatically. Does this have anything to do with my use of Nginx?
![image](https://user-images.githubusercontent.com/19728435/75603386-cb7c2c00-5b08-11ea-89d3-67c831ba1f97.png)

**Comment by pldubouilh** [comment]
what do you mean by refreshed ; it doesn't show up until you manually refresh the page ?
or is it an incorrect name that you need to manually amend ?

**Comment by sunlewuyou** [comment]
it doesn't show up until me manually refresh the page

**Comment by pldubouilh** [comment]
cool - I'll investigate :+1:
(it shouldn't be linked to your nginx setup btw)

**Comment by sunlewuyou** [comment]
This situation does not happen every time, sometimes 6 files are uploaded at once, and only 5 are automatically refreshed.

**Comment by sunlewuyou** [comment]
Maybe the reason for nginx

**Comment by sunlewuyou** [comment]
Thank you very much for your continuous updates ！

**Comment by pldubouilh** [comment]
I implemented a small delay in [v0.1.3](https://github.com/pldubouilh/gossa/releases/tag/v0.1.3), between when the upload's finished and the ui's refresh, so it'd leave some time for the last writes to be performed server side. Closing for now :+1:
