### ISSUE TITLE
Previous picture

### ISSUE THREAD

**Issue by aeeq** [pldubouilh/gossa#42]
Can I browse Previous picture without keyboard,such as on phone,now there's only the Next?

**Comment by pldubouilh** [comment]
there's no way to do that now, had a look some time ago but it seems there's no clean api for that in js, it has to be implemented manually :( 
I agree it's not ideal though, I'll think about it :+1:

**Comment by ChangePlaces** [comment]
how about storing the list of files as a json string / or an array in the html output of a directory, and passing that into whatever js you're using to view the image. I assume the whatever image overlay library / lightbox library you're using has a next / previous feature.

**Comment by pldubouilh** [comment]
there's no library whatsoever, everything's finely handcrafted haha :) 

the image list and image overlay are in place already, it's just about reading the swipe event in js, and reacting accordingly.

**Comment by pldubouilh** [comment]
actually js swipe events are absolutely available, I was looking at the wrong event on MDN. 
Swipe picture navigation is implemented in [v0.1.3](https://github.com/pldubouilh/gossa/releases/tag/v0.1.3) :+1:

**Comment by aeeq** [comment]
good!
