### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by ChangePlaces** [pldubouilh/gossa#43]
An api would be nice to be able to 

- create directory
- upload file
- get list of files and sub directories for a directory

**Comment by pldubouilh** [comment]
so a rest-ish api is available through the `/rpc` endpoint, it allows `mkdir`, `rm` and `mv` through a simple JSON structure e.g. `{"call":"mv","args":["/AAA", "/hols/AAA"]` - the [tests](https://github.com/pldubouilh/gossa/blob/master/src/gossa_test.go#L162) are probably a good place for checking it out. The upload is at `/upload`, and the files are at their natural path. The only API lacking is for file listing, as that's generated on the spot and filled into the html template the for faster / single request loads.

I should maybe document it out somewhere ~
