### ISSUE TITLE
windows cannot be used

### ISSUE THREAD

**Issue by zkf0802** [pldubouilh/gossa#47]
Will only listen on 127.0.0.1.
How to switch the monitored IP address。

**Comment by pldubouilh** [comment]
thanks for the feedback ! It's been a while I haven't used windows :) 
Do you have any clue what it could be ? I was thinking it could be the way ports/host is processed, or how the cli args are parsed. I'll look at booting up a VM somewhere when time allows.x

**Comment by petrst** [comment]
Hi,
I am running on Windows 10. In order to make gossa listening on all network interfaces start it this way
`gossa.exe -h 0.0.0.0 C:\Temp`

Cheers,
Petr

**Comment by pldubouilh** [comment]
cheers for the heads up @petrst !
I'm lacking a platform to test on, and as it seems to work I'll close for now - feel free reopen if you bump on the issue again :+1:
