### ISSUE TITLE
Cannot upload zip or rar files

### ISSUE THREAD

**Issue by mindfuucker** [pldubouilh/gossa#48]
Hi, 

I've been trying to upload zip or rar files. This does not seem to work. 

Is this intended behavior?

**Comment by pldubouilh** [comment]
hey - I just tested and zip / rar files are uploaded fine, just like any other data. there's no discrimination either on the UI or the server.
what's you setup (browser, how/where is gossa running) ?

**Comment by mindfuucker** [comment]
Gossa is running on docker with a volume outside docker.

Checking the network traffic in the DevTools tells me my reverse proxy (nginx) is the problem: 

Error: "413 Request Entity Too Large"

So sorry for hindering you.

**Comment by pldubouilh** [comment]
no problem, cheers for the follow up :+1: 
wow it seems the defaults on nginx are really small ! what config did you change in the end, just `client_max_body_size` ? I'd like to add that to an FAQ

**Comment by mindfuucker** [comment]
I changed client_max_body_size to 0 disabling the check.
