### ISSUE TITLE
Write Permissions Missing on Ubuntu18.04

### ISSUE THREAD

**Issue by awtrimpe** [pldubouilh/gossa#50]
I followed the steps exactly as they were on the [support page](https://github.com/pldubouilh/gossa/tree/master/support) using the dockerfile. The *LocalDirToShare* directory that was created did not have write permissions available to all users or the Docker instance was not seen as having elevated privileges to create or modify existing files.

Amending the created directory's permissions fixed the issue but there is probably a more user friendly solution.

**Comment by pldubouilh** [comment]
True, if the folder's not created beforehand docker will `sudo mkdir` it, making owned by root and then not reachable anymore by gossa which drops privileges before starting. Will include that step on the readme - cheers for the heads up :+1:

**Comment by pldubouilh** [comment]
coming in #54 - thanks for the heads up :+1:
