### ISSUE TITLE
raspberry pi 3 install

### ISSUE THREAD

**Issue by limitlessbritt** [pldubouilh/gossa#51]
Hi there, 
sorry I'm new to all this, I was wondering how do you install this on a raspberry pi 3? I have used caddy before so i understand that part, I'm just not sure how to build it.

Thanks!

**Comment by pldubouilh** [comment]
hello, just to clarify, do you plan on using it with docker or not ?

If not, I ship release builds so you don't really have to build it yourself, you can just download it on your rpi3 and run it. Then it depends on your caddy setup, but here's how you'd run it with default settings

```sh
wget https://github.com/pldubouilh/gossa/releases/download/v0.1.3/gossa-linux-arm64
chmod +x gossa-linux-arm64

# run on myfolder with default settings 
./gossa-linux-arm64 myfolder

# ... or run on myfolder, listening to all interfaces
./gossa-linux-arm64 -h 0.0.0.0 myfolder
```

**Comment by limitlessbritt** [comment]
Perfect that worked! For whatever reason when i downloaded and tried to run it, it wouldn't work. I'm not really sure why.

Just one more question I checked the help command but I don't see anywhere to create accounts, how do I go about doing that?

Thank you!

**Comment by pldubouilh** [comment]
there's no account support, it was purposefully left out, but it's very easy to use the proxy of your choice to have any kind of accounts/login.

For instance you can chain gossa with caddy using [this config](https://github.com/pldubouilh/gossa/blob/master/support/Caddyfile)
```
# start gossa
./gossa-linux-arm64 myfolder

# start caddy with example Caddyfile config (different shell)
./caddy
```

caddy also allows also for more complete setup (user `bob` gets to access only folder `bob`, etc..), I haven't published examples for that but will soon :)

**Comment by daninfuchs** [comment]
I'm confused - a friend and I are looking into using this software as a solution for our own unrelated projects, but I'm getting conflicting information from this issue and the project's page. I don't mean to be obtuse, but;

From your front page;
> 🔒 easy/secure multi account setup

From this issue;
> there's no account support, it was purposefully left out

I really don't mean to be offensive, please bear with me - Your software can't provide multi account setup without providing account support. Claiming to support it, but having to use an external program to implement it is like claiming my car will never run out of gas. It's true as long as I do all the work to implement that feature by keeping the tank full. That's not a car feature, that's a _me_ feature and a _gas station_ feature. Could advertise that it _supports gas stations_ but that's a bit obvious.

Can you clarify what "easy/secure multi account setup" means if it isn't something the software itself provides?

**Comment by andresmazzo** [comment]
Hi! Would be great arm and arm64 support, so we could implement **gossa** in SBC's and NAS's devices. 
I have been diving with lot of _Web based file managers_ and none of them has this support :sweat:

**Comment by pldubouilh** [comment]
@daninfuchs by `easy multi account setup` I meant that it's dead easy to route the requests through a third party tool like caddy, but not directly through gossa - that's why I said it's an easy setup, but it's not directly supported. I pushed lots of example in #54, checkout [support](https://github.com/pldubouilh/gossa/tree/master/support)

@andresmazzo arm and arm64 are supported, checkout the release page :+1:

**Comment by andresmazzo** [comment]
Great! Thanks @pldubouilh :raised_hands:
