### ISSUE TITLE
comics (cbr, cbz) support

### ISSUE THREAD

**Issue by greatcoco** [pldubouilh/gossa#52]
Works great already for PDF, can you add the support of cbr, cbz , basically a zip or rar containing images. This would make this a perfect all in one media viewer.

**Comment by pldubouilh** [comment]
that's not really planned - the only supported formats are whatever your browser can read. Maybe something is doable on the ui side to try decode that in JS and print it afterwards - feel free to investigate in this direction if you fancy :)
