### ISSUE TITLE
Feature request: download directory as archive

### ISSUE THREAD

**Issue by mindfuucker** [pldubouilh/gossa#53]
Hi,

I've been using gossa for over a month now and this is a feature I'm missing the most. The option to download the contents of a whole directory at once.

**Comment by pldubouilh** [comment]
hey - yes that's a bummer, sadly there's nothing easy that's doable... I'll keep the issue open see if something comes up

**Comment by mindfuucker** [comment]
Hey, 

I found [this project](https://github.com/filebrowser/filebrowser/blob/0b0a704d44f4890071332634d3cdd3af4725481f/http/raw.go) written in Go with an archiver build-in. 

You might be able to use it!

**Comment by pldubouilh** [comment]
cheers for the pointer - actually I implemented that yesterday weekend without dependencies (it was actually super short)
I'll cut a release with that feature this week :+1:
