### ISSUE TITLE
mp4 file doesn't play and cannot download

### ISSUE THREAD

**Issue by shorca** [pldubouilh/gossa#55]
Great work!

I noticed that when click on a video mp4 file, it fails to play and I don't find a way to download the video file. But I see it works in your demo. How do I debug?

Also, quick question: how to delete a file?

Thank you!

**Comment by pldubouilh** [comment]
thanks :) So for the mp4 files, it depends on your browser + codecs supported. Usually it works out of the box on firefox/chrome, but it might depend on a few other things (codecs used on the video of your mp4, support from your OS, etc...).
To download file, just right click a link and `save like as` - or `ctrl+enter` if you use the keyboard shortcut.

And to delete a file, double click on its icon - or `ctrl+backspace` for the keyboard shortcut (a help menu is available with `ctrl+h`)

**Comment by shorca** [comment]
Thank you! Very clear answer!
