### ISSUE TITLE
Add tagged deploy

### ISSUE THREAD

**Issue by josegonzalez** [pldubouilh/gossa#57]
It would be great to have tagged deploys to have some idea of stability :)

In addition, having tagged docker images would be 👍

**Comment by pldubouilh** [comment]
I'm not sure what you mean by tagged deploys ? I already [tag releases on github](https://github.com/pldubouilh/gossa/releases/tag/v0.1.4) and push blobs. I normally cut releases when there's change on the active codepath (so pretty much any change aside from readmes & buildfiles).

Also I just added [tagged docker builds](https://hub.docker.com/r/pldubouilh/gossa/tags), thanks for reminding me this :)

**Comment by josegonzalez** [comment]
Sorry yeah I meant docker tagged builds :) Thanks!
