### ISSUE TITLE
Enhancement/feature idea (zip, 7z, tar, tgz, etc.) archive file browsing

### ISSUE THREAD

**Issue by clach04** [pldubouilh/gossa#80]
Any thoughts on supporting browsing inside of archives so that files could be extracted and downloaded (perhaps added, renamed as well) via the web UI without downloading the entire (ZIP) archive?

This isn't something I desperately need but it would be something I could see myself using (I had a use case this evening where it would have been useful, it was a really large ZIP file that I did not want to pull down to my phone, I only wanted to look inside).

**Comment by pldubouilh** [comment]
yep, I thought of that before, it's doable but I'm not sure it'd fit within gossa's scope. 
maybe it could be the role of a middleware ?

**Comment by pldubouilh** [comment]
I'm closing, but I'd be interested to see if you
