### ISSUE TITLE
upload big file failed

### ISSUE THREAD

**Issue by Maple1401** [pldubouilh/gossa#82]
when i upload a big size movie  about 4G , just progress 4% then no response anythings.

so i used mount some folder to /shared way.

**Comment by pldubouilh** [comment]
interesting, I often push files over 4GB and it's plenty fast (filling my wifi bandwith at 80MB/s, so 4GB under a minute)

is the drive write speed following up ? and is the network following as well ?

**Comment by pldubouilh** [comment]
(closing as most probably not directly linked to gossa)
