### ISSUE TITLE
stream mkv's instead of download

### ISSUE THREAD

**Issue by Tone866** [pldubouilh/gossa#94]
I'm trying to stream h264 or h265 encoded mkv's, but I can only download them.
Im using MS Edge 114.
Is there some way to change this behavior? 
Thanks!

**Comment by pldubouilh** [comment]
hey ! Sadly it's a limitation from the browser - codec support is a bit of a hit and miss, and most of the time MKVs and h265 can't be opened natively...
You can stream directly from VLC by copying the URL and use the open from network functionality. I also plan on integrating the  `vlc://` scheme, but I need to test out support a bit before.

**Comment by jkaberg** [comment]
@pldubouilh most modern browsers support mkv and x265 (some hide it behind feature flags like chrome), I think its safe to allow *.mkv in https://github.com/pldubouilh/gossa/blob/master/ui/script.js#L582. The user still has the ability to copy link and use VLC etc if necessary
