### ISSUE TITLE
display error icon on error

### ISSUE THREAD

**Issue by pbogre** [pldubouilh/gossa#96]
I tried uploading some files and the upload kept failing because they were too large (i had to check the post request response through the developer settings in the browser)

turns out the problem was small `client_max_body_size` in my nginx configuration, but i think it would be helpful if instead of display the green checkmark icon when uploads like this fail, it displayed an error icon and maybe even the http response.

i wouldn't have been as confused if each time i tried uploading a file and it didn't show up i saw an error icon rather than a green checkmark

**Comment by pldubouilh** [comment]
ha it's very good to know, I'll dig into that - thanks for the report ! 

would you mind sharing the nginx config used ? I'll also mention it on the docs.

**Comment by pbogre** [comment]
Sure, here's the section that dealed with gossa in my nginx.conf:
```nginx
    # Gossa
    location /gossa {
      return 302 http://$host/gossa/;
    }
    location /gossa/ {
      proxy_pass http://gossa:8001/gossa/;
    }
```

and here's the line that i added at the top of my configuration to allow large upload files (i chose 100 MB as the max size, but it can be set to 0 to have no limits)
```nginx
    # increase maximum request size
    client_max_body_size 100M;
```
